dist: trusty
language: node_js
node_js:
  - 8
  - 10
cache:
  directories:
    - node_modules
    - packages/*/node_modules
before_install:
  - npm install -g npm
  - npm --version
script:
  - npm run build
