image: Visual Studio 2017

environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"

platform:
  - x64

cache:
  - node_modules
  - packages/dapp/node_modules
  - packages/gpcli/node_modules
  - packages/smartcontracts/node_modules

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm config -g set script-shell "bash"
  - npm install -g npm
  - npm install

before_build:
  - node --version
  - npm --version

build_script:
  - npm run build

test: off
